project_id = "eapnatbiodenijfrpqcn"

[functions.paperFinder]
verify_jwt = false

[functions.generatePodcastScript]
verify_jwt = false

[functions.processPaper]
verify_jwt = false

[functions.selectPaper]
verify_jwt = false